### PR TITLE
Experimental port to Zurb Foundation

### PR DESCRIPTION
**Pull request by avsm**
This (hopefully) improves the look-and-feel of the site, and definitely improves its cross-device and multiple-resolution performance.  I'm still testing it on some of the bigger packages such as Core, so not merging until there have been more eyes on it.

The main breakage is likely to be around the module inclusion.  This version doesn't cause the display to jump around when opening modules.  Ideally, module opening will leave the text aligned to the left and update a right-hand column with the module name (I haven't made this change yet, but I don't consider it critical).

### CODE REVIEW

**Comment by samoht** [comment]
```
$ opam doc uri
...
[3/4] Build the HTML pages
Generating documentation for ocamlfind
Fatal error: exception Parsing.Parse_error
Raised at file "src/opam-doc-index/html_utils.ml", line 206, characters 9-9
Called from file "src/opam-doc-index/html_utils.ml", line 296, characters 13-42
Called from file "src/opam-doc-index/driver.ml", line 188, characters 10-25
```

**Comment by avsm** [comment]
Upgrade your Cow to 0.9.1

**Comment by avsm** [comment]
Woah, that's not it at all.

```
Error while processing module Array_permute: "Parsing.Parse_error"
Error while processing module Avltree: "Parsing.Parse_error"
Error while processing module Bag: "Parsing.Parse_error"
Error while processing module Bigbuffer: "Parsing.Parse_error"
Error while processing module Bigbuffer_internal: "Parsing.Parse_error"
Error while processing module Bigstring: "Parsing.Parse_error"
Error while processing module Bigstring_marshal: "Parsing.Parse_error"
Error while processing module Bigsubstring: "Parsing.Parse_error"
```

Investigating...

**Comment by samoht** [comment]
Works better for me now (using cow 0.9.1). And it looks great!!!

**Comment by samoht** [comment]
Not sure if it is related to your PR, but after `opam doc cstruct`, I have http://127.0.0.1:8000/ocplib-endian/ and http://127.0.0.1:8000/optcomp/index.html#Pa_optcomp.Env which are empty (not in the same way, though).

**Comment by avsm** [comment]
I can reproduce the Parsing error on only some modules. It's reproducible with Lwt as a small test case. Looks like an instance of mirage/ocaml-cow#30

**Comment by avsm** [comment]
I've put up a snapshot at http://mirage.github.io/ that's accurate as of cb6d5ba

**Comment by lpw25** [comment]
There are also some visual inconsistencies. The font size on type definitions is wrong, and only their first line is highlighted. The resize buttons are too small and not centred. I think that the highlighting of first lines needs to use a different colour for different colour backgrounds (see http://mirage.github.io/cohttp/#Cohttp_lwt.Make_request). It is a bit strange that the include backgrounds are wider than the highlighted lines on the right but not on the left. I can't find any examples in the mirage libraries, but I'm worried about how it handles nested includes, does it still show the nesting? 

For includes, I would prefer them to be to the left of the text when expanded, as in the current version. Ideally, they would be on the left of the text (and out of the flow) when viewed on a large display (where there should already be a wide left margin for them to fit in), and inline with the text when viewed on small displays.

**Comment by avsm** [comment]
Thanks, I agree with all your points except for the module includes shifting left.  The issue with that (and the previous prototype) is that it caused the main body of the text to shift around, which is confusing.  I've played around with having the module types flush right instead, and it works surprisingly well.  However, it'll be easier to show this in person than to commit code as I did it by editing CSS in the browser directly.

For the other points, they're not easy to fix immediately, so I'll skip them until back in the office with a proper setup:
- The `typetable` and `code` need to be wrapped in a single `div` to give them a uniform background color (right now, only the first line is gray, as you observe).  This requires some refactoring in `generate.ml`.
- The reveal/hide logic can be done directly in Zurb using the helper classes (including better support for touchscreens), and I've integrated Font Awesome for the icons.  The icons will no doubt be useful elsewhere other than just these buttons, so I'll push a change to integrate them.  I won't modify your JavaScript until I'm back, as it would be good to nail down how we want it to work rather than messing around too much in this code.  We should be able to get a responsive design that collapses the module includes, as you suggest.

Should I just go ahead and merge this now, and do the tidyups in trunk?

**Comment by lpw25** [comment]
>  The issue with that (and the previous prototype) is that it caused the main body of the text to shift around, which is confusing.

It shouldn't (and didn't on the computer I was testing it with), the text body should stay in exactly the same place.

> Should I just go ahead and merge this now, and do the tidyups in trunk?

I doubt anyone is using trunk for anything, so you might as well.

**Comment by avsm** [comment]
I've merged this into trunk and opened up related issues for the outstanding problems.

**Pull request merged**
