### PR TITLE
Adding install to Makefile

### PR DESCRIPTION
**Pull request by heidihoward**
@lpw25 please check this carefully. I have little idea what I'm going. I am adding a "install" to the Makefile so I can add this to opam-repo-dev and the opam file can say:

 build: [
 [make "all"]
 [make "install" "BINDIR=%{bin}%"]

I'll not sure this is the best way to go about it, I've just been copying the style from lpw25/bin-doc

### CODE REVIEW

**Comment by lpw25** [comment]
This seems fine

**Comment by heidihoward** [comment]
`$ opam install opam-doc` is failing. I think its my implementation of "install" in the Makefile but I can't see the problem

==== ERROR [while installing opam-doc.0.1] ====
Internal error:
  Error while installing the following files:
- dist/build/opamdoc/opamdoc in /auto/homes/hh360/.opam/4.01.0+bin-doc/bin
  'opam install opam-doc' failed.

**Comment by lpw25** [comment]
Fixed

**Comment by heidihoward** [comment]
thanks

**Pull request merged**
