### PR TITLE
New version of the javascript and a lot of tidying up

### PR DESCRIPTION
**Pull request by lpw25**

### CODE REVIEW

**Comment by avsm** [comment]
Looks good! You have merge access, right?

**Comment by amirmc** [comment]
I'll do this now (both Leo and Philippe do have ability to merge).

**Comment by pw374** [comment]
My first impression is that it's loads Core.Std super super super fast!

**Comment by pw374** [comment]
cf. http://ocaml-redesign.github.io/pkg/docs/?package=core&module=Std

**Pull request merged**
