### PR TITLE
Fix #68

### LINKED ISSUE #68: Using opam-doc with the system compiler is broken
I've just cloned the repo and typed `make`. This gives me some errors while installing `ocamlfind`.

```
===== ERROR while installing ocamlfind.1.4.0 =====
# opam-version         1.1.1 (3305fa02cf8d135b0eff37d2418dcc20ff93bab5)
# os                   darwin
# command              ./configure -bindir /Users/thomas/git/opam-doc/opam/system/bin -sitelib /Users/thomas/git/opam-doc/opam/system/lib -mandir /Users/thomas/git/opam-doc/opam/system/man -config /Users/thomas/git/opam-doc/opam/system/lib/findlib.conf -no-topfind
# path                 /Users/thomas/git/opam-doc/opam/system/build/ocamlfind.1.4.0
# compiler             system (4.01.0)
# exit-code            1
# env-file             /Users/thomas/git/opam-doc/opam/system/build/ocamlfind.1.4.0/ocamlfind-99584-ffb3fd.env
# stdout-file          /Users/thomas/git/opam-doc/opam/system/build/ocamlfind.1.4.0/ocamlfind-99584-ffb3fd.out
# stderr-file          /Users/thomas/git/opam-doc/opam/system/build/ocamlfind.1.4.0/ocamlfind-99584-ffb3fd.err
### stdout ###
# Welcome to findlib version 1.4
# Configuring core...
### stderr ###
# configure: cannot determine ocaml's standard library directory
```

I guess this is because you've installed the `ocamlc` and `ocamlc.opt` which confuses ocamlfind configuration scripts when using the system compiler.

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
don't merge yet, there is still an issue.

**Comment by samoht** [comment]
Seems to work fine now.

**Comment by avsm** [comment]
could you add a travis for this? I've activated it on their site

**Comment by samoht** [comment]
I've simplified the use of opam-doc: now `make install` installs all the scripts and wrappers needed and the user just have to call `opam doc PKG1 ... PKGn` to generate and serve the documentation locally.

Ideally, the `opam-doc` script should be rewritten in OCaml completely and should take the base URIs as arguments if ones wants to export the documentation somewhere else (for instance, for RWO). @avsm what do you think ?

**Comment by samoht** [comment]
btw, Travis doesn't seem to pick my PR. And I don't have the right to merge it either.

**Comment by lpw25** [comment]
This all seems fine, although I'm a bit reluctant to make this prototype too easy to use, since I hope to completely rewrite it and merge it into opam2web. But since I won't get around to doing that for a while, I suppose we probably should make this version easier to use.

Also, I don't know how the Travis stuff works, but it seems to be testing it against OCaml trunk, which obviously won't work.

**Comment by avsm** [comment]
@lpw25 The `opam doc` interface can remain backwards compatible when the prototype is rewritten, but it's important we make this easier for other people to use and give us feedback.  @samoht, you're on the ocamllabs org owners set now.

**Comment by lpw25** [comment]
> The opam doc interface can remain backwards compatible when the prototype is rewritten

Thats my point: I don't want it to remain backwards compatible, nor do I really want feedback since it will just focus on what is broken in the prototype and how the prototype's output looks, both of which will change considerably in a rewrite. I am fine with making it easier to use anyway, I am just saying I would rather it was not used too widely.

**Comment by samoht** [comment]
@lpw25 I really want to use it ASAP (because I need it). So I'd prefer to have a slightly broken version of it now instead of a perfect one in few months. I'm fine to have a 2.0 with incompatible changes when the perfect version is ready.

**Comment by avsm** [comment]
By backwards compatible, I'm referring to the OPAM command line, not the output.

"opam doc core mirage" is a pretty simple way to generate the docs and hides the prototype details. Do you have a different CLI in mind ?

**Comment by lpw25** [comment]
> "opam doc core mirage" is a pretty simple way to generate the docs and hides the prototype details. Do you have a different CLI in mind ?

I was hoping to merge it into opam2web, so there wouldn't be a specific command for documentation. I suppose the "opam doc" command could activate opam2web and open your web browser to the right page, although then it only makes sense to specify a single package on the command line. It might be nicer for the `opam doc` command line tool to show something on the command line: perhaps an info version of the documentation (which obviously I want because then I can easily view documentation in emacs).

I also hope to avoid any explicit generation step. I think that documentation should be generated for all packages when they are installed (as long as opem2web is already installed).

**Pull request merged**
